/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.*;

/**
 *
 * @author holbe
 */
public class Calculator extends javax.swing.JFrame {
    private CurrencyLoaderFile currencies;
    private Currency[] toArray;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        currencies  = new CurrencyLoaderFile();
        currencies.loadAllCurrency();
        toArray = currencies.getCurrencies().toArray(new Currency[0]);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInput = new javax.swing.JPanel();
        currencyFromList = new javax.swing.JComboBox(toArray);
        currencyToList = new javax.swing.JComboBox(toArray);
        moneyInput = new javax.swing.JTextField();
        moneyFromInputLabel = new javax.swing.JLabel();
        currencyFromListLabel = new javax.swing.JLabel();
        currencyToListLabel = new javax.swing.JLabel();
        userOutput = new javax.swing.JPanel();
        moneyOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Divisas");
        setIconImage(new ImageIcon("conversorimage.png").getImage());
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        moneyInput.setText("");
        moneyInput.setPreferredSize(new Dimension(85,22));

        moneyFromInputLabel.setText("Importe");

        currencyFromListLabel.setText("De:");

        currencyToListLabel.setText("A:");

        javax.swing.GroupLayout userInputLayout = new javax.swing.GroupLayout(userInput);
        userInput.setLayout(userInputLayout);
        userInputLayout.setHorizontalGroup(
            userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInputLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moneyFromInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(moneyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currencyFromList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currencyFromListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currencyToList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currencyToListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        userInputLayout.setVerticalGroup(
            userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInputLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyFromInputLabel)
                    .addComponent(currencyFromListLabel)
                    .addComponent(currencyToListLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyFromList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyToList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        moneyOutput.setEditable(false);
        moneyOutput.setText("");
        moneyOutput.setPreferredSize(new Dimension(72,22));

        javax.swing.GroupLayout userOutputLayout = new javax.swing.GroupLayout(userOutput);
        userOutput.setLayout(userOutputLayout);
        userOutputLayout.setHorizontalGroup(
            userOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOutputLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(moneyOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userOutputLayout.setVerticalGroup(
            userOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userOutputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moneyOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public JTextField getMoneyOutput() {
        return moneyOutput;
    }

    public JComboBox<String> getCurrencyFromList() {
        return currencyFromList;
    }

    public JComboBox<String> getCurrencyToList() {
        return currencyToList;
    }

    public JTextField getMoneyInput() {
        return moneyInput;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currencyFromList;
    private javax.swing.JLabel currencyFromListLabel;
    private javax.swing.JComboBox<String> currencyToList;
    private javax.swing.JLabel currencyToListLabel;
    private javax.swing.JLabel moneyFromInputLabel;
    private javax.swing.JTextField moneyInput;
    private javax.swing.JTextField moneyOutput;
    private javax.swing.JPanel userInput;
    private javax.swing.JPanel userOutput;
    // End of variables declaration//GEN-END:variables
}
